#version: '3.7' # specify docker-compose version
## Define the services/containers to be run
#services:
#
#  frontend: #name of the first service
#    build: cook-book # specify the directory of the Dockerfile
#    ports:
#      - "4200:4200" # forwarding port
#    container_name: front-container
#    restart: always
#
#  backend: #name of the second service
#    build: cook-book-api # specify the directory of the Dockerfile
#    ports:
#      - "3000:3000" # forwarding port
#    container_name: back-container
#    restart: always
#    links:
#      - database # link this service to the database service
#
#  database: # name of the third service
#    build: database # specify the directory of the Dockerfile
#    container_name: database-container
#    restart: always

# Prod

version: '3.7' # specify docker-compose version
# Define the services/containers to be run
services:

  database: # name of the third service
    build: database # specify the directory of the Dockerfile
    container_name: database-container
    restart: always

  backend: #name of the second service
    build: cook-book-api # specify the directory of the Dockerfile
    ports:
      - "3000:3000" # forwarding port
    container_name: back-container
    restart: always
    links:
      - database # link this service to the database service

  frontend: #name of the first service
    build: cook-book # specify the directory of the Dockerfile
    ports:
      - "80:80" # forwarding port
    container_name: front-container
    restart: always





