openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:3000/api/
    description: None
paths:
  /recipes:
    get:
      summary: Returns all recipes
      description: empty
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Creates a reipe.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: number
                name:
                  type: string
                description:
                  type: string
                preparationTimeInMinutes:
                  type: number
                ingredients:
                  type: array
                  items:
                    type: object
                    properties:
                      _id:
                        type: number
                      name:
                        type: string
                      amount:
                        type: number
                      unit:
                        type: string
      responses:
        '201':
          description: Created

  /recipes/{id}:
    get:
      summary: Returns recipe by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    put:
      summary: Updates recipe with specified ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                preparation_time:
                  type: number
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
    delete:
      summary: Delete recipe with ID.
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
  /ingredients/{id}:
    get:
      summary: Returns recipe for recipe with id.
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
